MI-410: Send survey reminders
rifflearning/mattermost-plugin-riff-survey pull request #8
Opened 2019-05-27 13:21 UTC by chetanyakan

2019-05-28 07:43 UTC, harshilsharma63 requested changes

2019-05-28 07:43 UTC, harshilsharma commented on plugin.json
> +        "help_text": "Enter the message to be sent to users who have not responded to a survey yet."
Let's update this text to better represent how this message will be used.

```suggestion
        "help_text": "Enter the message to be sent to users as a reminder for filling pending surveys."
```

2019-05-28 07:43 UTC, harshilsharma commented on plugin.json
> +        "key": "ReminderCount",
Let's make this `MaxReminderCount`.

2019-05-28 07:43 UTC, harshilsharma commented on server/config/main.go
> +	if c.ReminderText == "" {
Add validations for  `ReminderCount` and `ReminderInterval`. Handle 0 and negative values.

2019-05-28 07:43 UTC, harshilsharma commented on server/platform/main.go
> +		time.Sleep(conf.ReminderIntervalDuration)
We don't want to use `time.Sleep` as this will cause too many threads to accumalate in the system, holding memory and other resources. Lets migrate this logic to use scheduling as discussed.

2019-05-28 09:42 UTC, chetanyakan commented on plugin.json
> +        "help_text": "Enter the message to be sent to users who have not responded to a survey yet."
Done.

2019-05-28 09:43 UTC, chetanyakan commented on plugin.json
> +        "key": "ReminderCount",
Done.

2019-05-28 09:43 UTC, chetanyakan commented on server/config/main.go
> +	if c.ReminderText == "" {
Done.

2019-05-29 11:00 UTC, chetanyakan commented on server/platform/main.go
> +		time.Sleep(conf.ReminderIntervalDuration)
Done.

2019-05-29 11:27 UTC, harshilsharma63 approved these changes

2019-05-29 11:27 UTC, harshilsharma commented on server/model/util.go
> +func DecodeStringArrayFromByte(b []byte) []string {
Let's see if we can make them interface to []bytes instead of limiting to []string.

2019-05-29 11:27 UTC, harshilsharma commented on server/model/survey.go
> +// ReminderMetadata stores metadata related to the reminder settings for a survey
Now that we are adding type functions, lets' split types into separate files to keep things clean.

2019-05-29 12:27 UTC, chetanyakan commented on server/model/survey.go
> +// ReminderMetadata stores metadata related to the reminder settings for a survey
Done.

2019-05-29 16:35 UTC, chetanyakan commented on server/model/util.go
> +func DecodeStringArrayFromByte(b []byte) []string {
- Updated `StringArrayToByte` to use interfaces.
- For `DecodeStringArrayFromByte`, it is better to return an explicit type. Since otherwise, we would have to add multiple type assertions: for the array and then each element in the array.

2019-05-29 16:36 UTC, merged